### PR TITLE
WIP - Setup toggle buttons for timeline actions

### PR DESCRIPTION
**Pull request by speedytechdev**
Added classes for buttons so it is easy to code them. I also setup alignments for them so they look nice and clean. (These buttons are not programmed yet and don't work)

### CODE REVIEW

**Comment by ferdnyc** [comment]
Very cool! I've been hoping to see graphical controls (of _any_ sort on the Timeline tracks for a **long** time now. (It's a GUI, we should be using it as such. Not everything needs a context-menu toggle.)

One request: If this PR isn't ready to be merged yet, can you mark it "WIP" in the beginning of the title, to let everyone know it's currently a "Work In Progress"? That'll protect against it possibly being merged in a state where you're still working on it.

Looking forward to seeing this, please let us know when it's ready for testing!

**Comment by speedytechdev** [comment]
@ferdnyc Thanks and Sorry I forgot to add it.

**Comment by peanutbutterandcrackers** [comment]
I believe [this](https://ksr-ugc.imgix.net/assets/000/400/694/e32f70529823094f375fd83ab58a8f29_original.png?ixlib=rb-1.1.0&w=680&fit=max&v=1361466081&auto=format&gif-q=50&lossless=true&s=3d73bf49fd91cf53bfa1c31ec08b7a07) is where this PR is eventually going to get to (or is setting up the stage for)?

Speaking of PR, again, the changes seem to have been made on the `develop` branch itself, rather than a branch that is branched off of `develop`. It would have been easier to keep this clean and organized if things were organized into self-contained branch. [Ferdnyc's branches](https://github.com/ferdnyc/openshot-qt/branches) should give you a clearer idea of what I mean.

Great work, BTW! :+1:

**Comment by speedytechdev** [comment]
> I believe [this](https://ksr-ugc.imgix.net/assets/000/400/694/e32f70529823094f375fd83ab58a8f29_original.png?ixlib=rb-1.1.0&w=680&fit=max&v=1361466081&auto=format&gif-q=50&lossless=true&s=3d73bf49fd91cf53bfa1c31ec08b7a07) is where this PR is eventually going to get to (or is setting up the stage for)?
> 
> Speaking of PR, again, the changes seem to have been made on the `develop` branch itself, rather than a branch that is branched off of `develop`. It would have been easier to keep this clean and organized if things were organized into self-contained branch. [Ferdnyc's branches](https://github.com/ferdnyc/openshot-qt/branches) should give you a clearer idea of what I mean.
> 
> Great work, BTW! 👍

I knew I had to do something thanks. Also, what would be an easy way to make these changes into a new branch?

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers "I believe this is where this PR is eventually going to get to (or is setting up the stage for)?" Yes that is the plan.

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers I think I made a new branch now.

**Comment by ferdnyc** [comment]
Heh, I was just in the middle of typing out an explanation why you didn't _have_ to do that, but still it's easier (for yourself) that you did. And, yep, the `speedytechdev:Setup-toggle-buttons-for-timeline-actions` branch looks good.

Now, here's the bad news. Because a PR is associated with a source branch, you're going to have to close this PR, and open a new one from the new branch. Sorry! :roll_eyes:

**Comment by speedytechdev** [comment]
https://github.com/OpenShot/openshot-qt/pull/2212

**Pull request closed without merging**
