### PR TITLE
Add thumbnail to the audio only clip

### PR DESCRIPTION
**Pull request by SuslikV**
The audio only files has thumbnail rendered as black rectangle in the Timeline (v2.5.0).
Screenshot is here: https://github.com/OpenShot/openshot-qt/issues/3248

### CODE REVIEW

**Comment by SuslikV** [comment]
Github working strange for me... Probably, I have missed semicolon at the end of the `return` line but not sure if I'm able to fix this right now.

**Comment by SuslikV** [comment]
Such a perfect error in CI logs:

>... AttributeError: module 'openshot' has no attribute 'OPENSHOT_VERSION_FULL'

it was mentioned couple of times for linux PPA builds (for example, https://github.com/OpenShot/openshot-qt/issues/3235#issuecomment-590540210 )

**Comment by ferdnyc** [comment]
> Such a perfect error in CI logs:
> 
> > ... AttributeError: module 'openshot' has no attribute 'OPENSHOT_VERSION_FULL'
> 
> it was mentioned couple of times for linux PPA builds (for example, [#3235 (comment)](https://github.com/OpenShot/openshot-qt/issues/3235#issuecomment-590540210) )

That happens when building (or running) newer code with an outdated `libopenshot.so` — in this case, Travis seems to have decided to install the following versions:
```
Selecting previously unselected package libopenshot-audio6:amd64.
Preparing to unpack .../078-libopenshot-audio6_0.1.5+dfsg1-1_amd64.deb ...
Unpacking libopenshot-audio6:amd64 (0.1.5+dfsg1-1) ...
Selecting previously unselected package libopenshot14:amd64.
Preparing to unpack .../084-libopenshot14_0.1.9+dfsg1-3build1_amd64.deb ...
Unpacking libopenshot14:amd64 (0.1.9+dfsg1-3build1) ...
Setting up libopenshot-audio6:amd64 (0.1.5+dfsg1-1) ...
Setting up libopenshot14:amd64 (0.1.9+dfsg1-3build1) ...
```
...Which, since we're currently up to `libopenshot-audio7 / 0.1.9` and `libopenshot18 / 0.2.4`, worked out about as well as you'd expect.

Travis gets screwy sometimes. I'll restart the build, and it'll no doubt go through without incident. (Unless the PPA has actually gotten broken somehow.)

**Comment by ferdnyc** [comment]
Yup, as predicted, the restarted job flew right through with no issues.

**Comment by SuslikV** [comment]
Strange that it happens.

**Comment by ferdnyc** [comment]
Tested the PR branch, works nicely! Merging, thanks @SuslikV .

**Pull request merged**
