### PR TITLE
This fixes improves the user experience !!

### PR DESCRIPTION
**Pull request by olielvewen**
This work resolve an issue with buttons of the timelinezoobar which were inversed.
This work improve the number of transitions to near 500.
This work improve the number of titles 2D.
@jonoomph 
The issue I was getting when I've run openshot has disappeared without doing nothing. I've just power on my computer the day after. Probably too much memory used since a whole day to testing each modification.

### CODE REVIEW

**Comment by jonoomph** [comment]
Hey Olivier, I think we need to hold off adding lots of new "translatable" items into openshot-qt. Also, I fixed quite a few issues on the French translations (the %s placeholder was capitalized in a few places, and replaced with %2 in once case). There are a few critical bugs with exporting and audio pops that I need to address first, and then we can resume merging this branch. Thanks!

**Comment by olielvewen** [comment]
Okay, I've done others fixes.
This fixes change our bug and questions web page like we are moving our developement on Github. Anyway, it will be better for us for manage the Qt bugs.
The last fixe change the shortcut of the Splitting Dialog in the contectual menu in the file tree. THe older can be confusing for th user with this one for the export dialog.

**Comment by olielvewen** [comment]
Hey, Jonathan I 'm totally agree with you but did you know that you can merge only a part of my stuff/work and not all. LIke I'm able to work on this branch.
Did you know that you could create several branch keeping the master branch clean ? 
It is so easy to play with branch. What tool !!!!!

**Comment by Jo-Con-El** [comment]
The file "src/titles/Bubble_hight.svg" should be renamed to "src/titles/Bubble_high.svg" (superfluous 't').

**Comment by olielvewen** [comment]
Hi Jonathan,

I've finally find how to update my branch if you don't still have done.

**Comment by jonoomph** [comment]
I'm going to close this for now, since I don't want to increase the size of our installers and translations any more than they already are... and we already have so many great transitions. Thanks though.

**Comment by peanutbutterandcrackers** [comment]
Since good @olielvewen is the 2nd most prominent contributor to this project according to GitHub stats the last time I checked, I hope to see you around again with more neat contributions, good sir.

As for the 2D titles, I really think it'd be nice if we could get a few more of them in OpenShot. :) [I'll try to look these up, soon and see how they look, though. :) ]

**Pull request closed without merging**
