### PR TITLE
Nudge clips

### PR DESCRIPTION
**Pull request by N3WWN**
Nudging of clips can now be performed by selecting the clip(s) on the timeline and using <kbd>Shift</kbd>+<kbd>Left</kbd> or <kbd>Shift</kbd>+<kbd>Right</kbd>.

Minimum nudge amount is 0.01s or 1/2 frame duration, whichever is more.  

For instance, a  15 FPS project will nudge clips by 1/2 a frame or ~0.03s (1/15 * 1/2), but a 60 FPS project will nudge clips by 0.01s because 1/2 frame is 0.008s (1/60 * 1/2).

I know I saw an email or issue or something where this was requested, and I know that I will use it all the time, but I can't find the issue to reference here.

### CODE REVIEW

**Comment by jonoomph** [comment]
This looks very cool, however it introduces new translatable elements, and for that reason I'm going to merge this after our release. Sorry, if I knew this was ready, I should have merged it before a call for translations.

**Comment by ferdnyc** [comment]
Nice, @N3WWN , this sounds great! Very handy.

OOC, what's the behavior when a clip is nudged up against another clip on the timeline? (For example, say I use "Slice: Keep Both Sides" on a clip, select the right-hand slice, and then press "Nudge Left".) Will it push the other clip? Overlap it? Refuse to be nudged because there's something "in the way"?

**Comment by DylanC** [comment]
@N3WWN @ferdnyc - Should this PR be targeting the develop branch now instead of master?

**Comment by N3WWN** [comment]
I'm not entirely sure... it was ready to go in 2.4.2, but @jonoomph said the translation request was missing the items for it, so it was held off.

**Comment by DylanC** [comment]
@N3WWN - No worries, I'm just a bit confused over the branching we are doing now. I think we are to merge to the develop branch going forward. I'd like to get this in but its current targeting the master branch. (which may not be correct currently)

**Comment by ferdnyc** [comment]
> @N3WWN - No worries, I'm just a bit confused over the branching we are doing now. I think we are to merge to the develop branch going forward. I'd like to get this in but its current targeting the master branch. (which may not be correct currently)

Exactly, under [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) master only contains released code, and is never merged to except from release branches. It's [by far the worst thing about the model](https://github.com/OpenShot/libopenshot/issues/103), since it goes against every established Git convention and makes things needlessly confusing. But, it's where we're at now.

Which means any PRs made against `master` need to be rebased to `develop`. 

If you're working in a local repo that's set up like mine, cloned from your fork but with https://github.com/OpenShot/openshot-qt.git set as a second remote (`upstream` in my config), and with the local `develop` branch being checked out from (and tracking) `upstream/develop`, then I believe you can just do:
```sh
git checkout branch_for_pr
git rebase develop
git push -u origin branch_for_pr --force
```
And the PR will automatically be updated accordingly. (You have to `--force` the push, because the rebase requires it to rewrite history on the remote side (your fork).)

...But sometimes it's easier to just generate a new PR, comparing against `OpenShot:develop` as the base.

**Comment by N3WWN** [comment]
Thanks @ferdnyc !

@DylanC - I'll try to get this PR rebased to the develop branch before the weekend.

**Comment by N3WWN** [comment]
Looks like, after following @ferdnyc 's instructions, this PR is still against `OpenShot:master`, so I'm going to close it and submit a new PR from my fork which currently shows it is against `OpenShot:develop`.

**Comment by ferdnyc** [comment]
Yeah, I hadn't actually tried that myself, figured it was worth a try. You needed to do the rebase on your branch anyway, to submit the new PR, so I figured it couldn't hurt to try. This way the branch was already ready already.

**Comment by N3WWN** [comment]
> This way the branch was already **ready** **_already_**.

🤣 It did save me a TON of work, that's for sure!  Thanks!

**Comment by ferdnyc** [comment]
You know, now I'm second guessing myself on that. A merge involves git comparing two branches from the point where they diverge, figuring out which which changes the head branch has that the base doesn't, and joining those to the base. Even if a PR is coming from a branch that isn't based off the target branch, as long as they still have a common ancestor SOMEWHERE, git can do its thing. It's plausible that the new PR would've looked _exactly_ the same even if you hadn't rebased. Git is crazy and kind of awesome that way.

(You'd have ended up pulling back the bits of develop your branch didn't already have when they were merged into your PR branch, too. So for sure the result would've been the same in the end.)

**Pull request closed without merging**
