### PR TITLE
Fix another regression in Windows Installer

### PR DESCRIPTION
**Pull request by jonoomph**
One more syntax error in the description (from https://github.com/OpenShot/openshot-qt/pull/2872). Also, I haven't tested this one yet, but is `cm:AssocFileExtension` this defined somewhere?

### CODE REVIEW

**Comment by ferdnyc** [comment]
Heh! Whoops, sorry. The `windows-installer.iss` changes were necessarily untested, since I didn't have a Windows system _with_ a fully-built copy of all three project repos to run through InnoSetup, in order to confirm they'd actually, you know, "work".  😇

**Comment by ferdnyc** [comment]
(Probably would've been gentlemanly of me to _mention_ that, however...)

**Comment by jonoomph** [comment]
No worries, almost fixed... I think. Fingers crossed.

**Comment by jonoomph** [comment]
Yup, just missing a `}`. Everything works correctly with `*.osp` associations + installer tasks.

**Comment by ferdnyc** [comment]
Drew-got-animated-during-her-acceptance-speech

**Pull request merged**
