### PR TITLE
Update inkscape files to the new higher DPI

### PR DESCRIPTION
**Pull request by JacksonRG**
- Opened each inkscape file.
- Allowed inkscape to re-scale each file while preserving
  their appearance, and saved the file

Warning message from Inkscape:
Inkscape-warning

### CODE REVIEW

**Comment by jonoomph** [comment]
Did this actually update the DPI from 90 to 96? I've attached the warning image to the description of this ticket.

**Comment by JacksonRG** [comment]
I believe it did. But I'll look to verify. It made the files open without that warning afterwards.

**Comment by jonoomph** [comment]
Sounds good. LGTM

**Comment by ferdnyc** [comment]
@JacksonRG 

> - Opened each inkscape file.
> - Allowed inkscape to re-scale each file while preserving
>   their appearance, and saved the file

Wow, I'm really sorry you went through all of that! It wasn't necessary. Pure-vector Inkscape files (like ours) don't have an intrinsic DPI (some other files do, if they're designed to specific dimensions for real-world output, like pre-press designs) but ours don't). If you look at the diff, the only thing that changed with reopening and resaving them is:
1. A few size values at literally the EIGHTH decimal point (`0.39215687` -> `0.39215686`, for example)
2. The session metadata (meaning, the dimensions of your inkscape application window were stored, replacing the previously-saved values from whoever last edited the files)
3. **The Inkscape version number**

The last one is the critical one, because Inkscape won't offer to update files if they were saved with a version newer than 0.92. So, this change will prevent that message coming up in the future. It could've been fixed with a batch script, but what's done is done.

**Comment by JacksonRG** [comment]
> Wow, I'm really sorry you went through all of that! It wasn't necessary.

Oh it was no issue. I just selected all, opened, and waited. :laughing:

And good to know. While a script is a good idea, I like letting inkscape edit svgs, as that's its job.

I appreciate the info! I was dragging my feet to merge this, as I wasn't positive how I could prove I didn't mess up the scaling on any of our titles.

**Comment by JacksonRG** [comment]
@ferdnyc Just rolled back everything but the version number! Planning to merge once the tests pass

**Pull request merged**
