### PR TITLE
WIP: Reduce logspam

### PR DESCRIPTION
**Pull request by ferdnyc**
OpenShot outputs a staggering number of unnecessary, redundant, or generic messages to its log while running, especially on startup. 

(A log message every time a fallback icon is used; every time an interface binding is created; every time an effect is loaded — that one just says "effects_model:INFO category: Video" every time, so _super_ useless; every time the preview is resized; etc...)

The user doesn't care about _any_ of these, and honestly they're of no help to developers either. They're just the equivalent of debug `printf()`s being left in the code. So, this PR aims to wipe them out. 

Along the way, I'm fixing the type of some other messages (lowering some from `log.info()` to `log.debug()`, promoting others from `log.info()` to `log.error()`, etc.) and updating the formatting of any that use Python %-string formatting to instead use `str.format`.

WIP because I still have more files to go through.

### CODE REVIEW

**Comment by ferdnyc** [comment]
- [ ] **Note to self:** Tackle the blender code next, because it is _obscene_ how much crap gets spewed on the console when using the Animated Titles editor. I mean, FFS:

```console
     ui_util:INFO Initializing UI for Dialog
blender_model:INFO updating effects model.
blender_listview:INFO File Name
blender_listview:INFO Title
blender_listview:INFO Extrude
blender_listview:INFO Bevel Depth
blender_listview:INFO Font Name
blender_listview:INFO Bfont
blender_listview:INFO Text Alignment
blender_listview:INFO CENTER
blender_listview:INFO Text Size
blender_listview:INFO Text Width
blender_listview:INFO Diffuse Color
blender_listview:INFO Specular Color
blender_listview:INFO Specular Intensity
blender_listview:INFO Start Frame
blender_listview:INFO End Frame
blender_listview:INFO Animation Length
blender_listview:INFO 2
blender_listview:INFO 1
blender_listview:INFO init_slider_values
blender_listview:INFO sliderPreview_valueChanged: 1
blender_listview:INFO sliderPreview_valueChanged: 125
blender_listview:INFO btnRefresh_clicked
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO preview_timer_onTimeout
blender_listview:INFO Blender command: blender -b '/home/ferd/rpmbuild/REPOS/openshot-qt/src/blender/blend/wireframe_text.blend' -P '/home/ferd/.openshot_qt/blender/7323d7c0-86b5-11e8-a60c-2c27d72bd51f/wireframe_text.py'
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
CUDA cuInit: Unknown error
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
# XXX
# (I removed literally _THIRTY_ of these identical lines)
# XXX
blender_listview:INFO Image detected from blender regex: [('/home/ferd/.openshot_qt/blender/7323d7c0-86b5-11e8-a60c-2c27d72bd51f/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
blender_listview:INFO onRenableInterface
blender_listview:INFO QThread Render Method Invoked
blender_listview:INFO Blender command: blender -b '/home/ferd/rpmbuild/REPOS/openshot-qt/src/blender/blend/wireframe_text.blend' -P '/home/ferd/.openshot_qt/blender/7323d7c0-86b5-11e8-a60c-2c27d72bd51f/wireframe_text.py'
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
X server found. dri2 connection failed! 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
CUDA cuInit: Unknown error
blender_listview:INFO Image detected from blender regex: []
# XXX
# And another 30 here!
# XXX
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: [('/home/ferd/.openshot_qt/blender/7323d7c0-86b5-11e8-a60c-2c27d72bd51f/TitleFileName0125.png', '')]
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Image detected from blender regex: []
blender_listview:INFO Blender render thread finished
blender_listview:INFO onRenableInterface
```
...Anyway, point is that's completely insane.

**Comment by peanutbutterandcrackers** [comment]
Can't wait till this PR is no longer WIP. Should be really helpful in keeping the logs succinct :)

**Comment by DylanC** [comment]
@ferdnyc - I think the line endings change has impacted this one (also).

**Comment by ferdnyc** [comment]
Replaced with #1905.

**Pull request closed without merging**
