### PR TITLE
Updating translations: Oct 29, 2021

### PR DESCRIPTION
**Pull request by jonoomph**
Fixing broken translations mentioned in https://github.com/OpenShot/openshot-qt/pull/4501

### CODE REVIEW

**Comment by ferdnyc** [comment]
@jonoomph 

There was a _fake_ **language** in the translations?!? Well, that's bizarre!

**Comment by jonoomph** [comment]
@ferdnyc Yes, it appears that a user manually uploaded a `gaa` language in Launchpad.net, and internally it identifies as the `ga` language. But I can't seem to find a way to delete the `gaa` language now. :shrug:

**Comment by ferdnyc** [comment]
@jonoomph Oy. We really should switch to Crowdin or some other service. Launchpad was... "fine", at the time, but there are way better options these days, from services dedicated to translation as their sole focus. 

Including plenty that support .ts files directly, so we wouldn't have to round-trip everything from .ts to .pot to .po and back to .ts again.

**Comment by ferdnyc** [comment]
@jonoomph 

A user also made the very good point, a couple of months ago, that we should really be checking the .ts files into the repo, instead of (or in addition to) the compiled .qm files. While it's possible to decompile .qm using Linguist, useful information like the source file references is lost when they're compiled. So users who want to contribute translations have no option but to use the very disconnected approach that is Launchpad.

(Disconnected compared to using Linguist. Which, thanks to Qt for Python, can now use source file references to display translation strings in their original context, in Python same as in C++. It's actually kind of cool.)

`pylupdate` has the same ability to extract message strings from Python code as `gettext` does, and it's possible to configure it to understand `_` as an alias for `translate()` / `tr()`.

**Comment by ferdnyc** [comment]
@jonoomph 

I worry that our current approach may not be providing translators with all of the information they need (or would ideally like to have, at any rate) in order to translate the interface. The whole "only one translation per unique string" restriction is a severe imposition, and ignores the reality that the same word(s) can have VERY different meanings in different contexts. The lack of any support for plural translations has also been brought up as an ongoing problem (by the same user who suggested providing access to the .ts files, IIRC).

**Comment by ferdnyc** [comment]
@jonoomph 

See #3589 #4326

**Pull request merged**
