### PR TITLE
WIP - Timeline actions for #1993

### PR DESCRIPTION
**Pull request by speedytechdev**
[timeline.zip](https://github.com/OpenShot/openshot-qt/files/2453854/timeline.zip)

Added classes for buttons so it is easy to code them. I also setup alignments for them so they look nice and clean. (These button are not programmed yet and don't work)

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
@speedytechdev - Hey, um... you might probably want to re-do this PR and try making this merge request into `develop` rather than master. The thing is, `develop` is the default branch, and not master - for OpenShot. So all the development works are done in develop and then we create a release branch off of it and then when a new version is released, the release branch is merged into master.

Also, You might want to explain your changes in a bit more detail in the description so that the code reviewers might have a better understanding of what you are trying to do.

Thank you for trying to make OpenShot better!

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers Thanks for that :)

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers I have a problem it won't let me master to develop.
image
image

**Comment by peanutbutterandcrackers** [comment]
@speedytechdev - So, the way you do this is:
1. Fork openshot on GitHub (sorry I am being overly precise)
2. Cone your repo onto your local machine
3. `git checkout develop` to go to your local develop branch
4. `git branch your_feature_name` to create a new branch where you will develop your features
5. `git push -u origin your_feature_name` to push your local branch to your GitHub account
6. Now go to your GitHub fork of OpenShot, go to branches - you should see n+1 branches listed (where n is the number of branches you previously had). Click on your branch and then create a pull request using the button.

That is the basics. Also, you would want to be keeping track of the upstream (the actual openshot repo) during this time to make sure you are up to date with it. For that you may find [this video](https://www.youtube.com/watch?v=-zvHQXnBO6c) helpful.

Hope that helps!

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers Thanks but I am a bit stuck. Where do I put those commands in?

**Pull request closed without merging**
