### PR TITLE
Rename frozen executable to openshot-qt

### PR DESCRIPTION
**Pull request by ferdnyc**
This renames the executable created by cx_Freeze from `launch`/`launch.exe` to the value of `info.NAME` (currently `openshot-qt`), plus the appropriate extension (if any), so that a running OpenShot will show up in process listings as "openshot-qt" rather than the generic/suspicious-seeming "launch".

It also renames any scripts that call or access `launch.exe`/`launch` to use `openshot-qt.exe`/`openshot-qt` instead.

### CODE REVIEW

**Comment by SuslikV** [comment]
It also changes file info that is part of the https://github.com/OpenShot/openshot-qt/issues/2762 suggestion.

**Comment by ferdnyc** [comment]
> It also changes file info that is part of the #2762 suggestion.

\*nod\* I had a bigger set of Windows-specific changes to come (companion to my #2769 PR that addressed the Mac side of things), but your versioning / pywin32 findings in #2772 convinced me you've made way more/better progress on that front than I have so far. I also realized I wanted to change the launcher name on _all three_ platforms, so I broke this one out.

I'll still have a (smaller) set of Windows-specific changes to come — tweaks to the icon, if nothing else (larger sizes, since `64x64` is pathetic as a max size in a HiDPI / Win10 world) and probably the installer package metadata (different from the executable metadata). Might take me a few more days to finish readying those, though. My Win7 VM is slow as crap and a chore to work in. :grimacing:

**Comment by SuslikV** [comment]
I'm using only appveyour to test such things (Windows based build). So, my setup is no way better... ^_^ (the https://ci.appveyor.com/project/SuslikV/openshot-qt/build/artifacts)

**Comment by jonoomph** [comment]
This is going to break some stuff, especially related to packaging scripts. Let me do some poking around on "what will break" before I merge this. :wink:

**Comment by ferdnyc** [comment]
@jonoomph It _miiight_ — certainly, the stuff outside of the OpenShot repos, like the PPA builder and whatnot, or the AppImage builders, may need tweaking — but at least _within_ the environment I think it should be OK. I looked hard for every dependency I could find on the actual name, and came up with a lot fewer than I expected, happily. And our Fedora packaging scripts _already_ make this change, so all I have to do is **remove** a `mv` command there and we're all set. :grin:

**Comment by jonoomph** [comment]
You are probably correct. All packaging scripts will likely need to be updated to handle the change in executable name... but locally, it's not that big a deal. This is why I've dragged my feet on this change (it's been on my mind forever). So, perhaps now is the time.

**Comment by ferdnyc** [comment]
Way I see it: There will never be a _good_ time... so, no reason to wait! :laughing:

**Comment by ferdnyc** [comment]
(Well, the only argument I **can** see for waiting: It'd probably be polite to include a heads-up in the release notes for the next release, since this will require action by packagers and etc. So it may make sense to wait until that's closer to happening, that way it's still a recent thing and doesn't get left out or take people by surprise. Because, who can remember the stuff they broke two months earlier? Not I!)

**Comment by SuslikV** [comment]
The only real disadvantage of this change is that the icon file in windows has same name `openshot-qt`. And as soon as default behavior for Windows is not to show the file extension of `.exe` and `.ico` files, the manual start of the application confuses me - I don't know which file to launch - they both look the same... By the way, some other Windows applications also has this issue, when they like to store `.ico` file together with the `.exe` in the same folder.

**Comment by ferdnyc** [comment]
> The only real disadvantage of this change is that the icon file in windows has same name `openshot-qt`. 

That's... true, but feels like a really minor downside. I think the advantages to this far outweigh the negatives to keeping the process named `launch.exe`, no? I'd rather rename the icon file as well, if it really mattered — but I don't think it matters.

> And as soon as default behavior for Windows is not to show the file extension of `.exe` and `.ico` files, the manual start of the application confuses me - I don't know which file to launch - they both look the same... 

There's a very simple solution to that: Turn off extension hiding! It's one of the first things I do on any Windows machine (along with turning on hidden-folders display). Most users will never even look inside the application folder, there's no reason for them to. The ones who do, I trust are savvy enough to solve this non-problem for themselves.

> By the way, some other Windows applications also has this issue

Exactly. This is incredibly common. And the way I see it, it's really _Windows'_ issue, not ours.

**Comment by SuslikV** [comment]
Nope, it's yours issue, because you shouldn't store icons as standalone files when working with Windows.

**Comment by ferdnyc** [comment]
So delete the icon file. You have my permission.

**Comment by SuslikV** [comment]
Yes, sir! Would you like to remove it for all enemies or only in my PC?

**Comment by ferdnyc** [comment]
@SuslikV If removing it doesn't break anything, I have no issues with it being removed from the installer package. I don't _believe_ it should cause any problems — every installed component uses the `.exe` file  as the icon source. And the InnoSetup configs reference it from the source tree (`../xdg/openshot-qt.ico`), not the build tree, so there's really no reason it needs to be included in the build directory at all.

Removing this line from `freeze.py` would probably do it:
```python
    src_files.append((os.path.join(PATH, "xdg", iconFile), iconFile))
```

**Comment by SuslikV** [comment]
Yeah, it is just source file. Thank you for the info @ferdnyc .

**Comment by ferdnyc** [comment]
@SuslikV 

I've added a commit to remove `openshot-qt.ico` file from the packaged files to PR #2872.

**Comment by SuslikV** [comment]
@ferdnyc It is better to remove the link from the commit's message.

**Comment by ferdnyc** [comment]
> @ferdnyc It is better to remove the link from the commit's message.

Funnily enough, there's no link in the commit message. It just says `#2796`. GitHub automatically picks that up as an issue/PR number and converts it into a link, but only in their web interface.

```diff
$ git show a06124c6
commit a06124c6 (HEAD -> win-install, origin/win-install)
Author: FeRD (Frank Dana) <ferdnyc@gmail.com>
Date:   2019-07-17 11:45:32 -0400

    Don't package openshot-qt.ico on Windows
    
    The icon resources will be incorporated into the `launch.exe` file
    (which picks up its icon resources from `xdg/` in the source tree,
    not from the packaged files), so there's no reason so separately
    include the `.ico` file itself as well.
    
    Addresses file same-name issues raised in #2796.

diff --git a/freeze.py b/freeze.py
index b083781d..082d7c9d 100644
--- a/freeze.py
+++ b/freeze.py
@@ -149,7 +149,6 @@ if sys.platform == "win32":
 
     # Append Windows ICON file
     iconFile += ".ico"
-    src_files.append((os.path.join(PATH, "xdg", iconFile), iconFile))
 
     # Append some additional files for Windows (this is a debug launcher)
     src_files.append((os.path.join(PATH, "installer", "launch-win.bat"), "launch-win.bat"))
```

**Comment by jonoomph** [comment]
Resolved some conflicts... getting ready to merge this one. I'm 37% worried about this one causing issues across our build servers and community. But like you said, there is really no great time for this type of change, and I agree it's an important change.

**Comment by jonoomph** [comment]
Ahh, all 3 build servers failed on this one: 
```
<module 'cx_Freeze' from '/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/__init__.py'>
Copying modules to openshot_qt directory: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot_qt
Loaded modules from openshot_qt directory: /home/gitlab-runner/builds/5cd61c66/0/OpenShot/openshot-qt/openshot_qt
Traceback (most recent call last):
  File "freeze.py", line 286, in <module>
    copyright = info.COPYRIGHT)])
TypeError: __init__() got an unexpected keyword argument 'copyright'
ERROR: Job failed: exit status 1
```

**Comment by jonoomph** [comment]
Windows error:
```
      freeze:INFO Execution path: C:\Users\Administrator\builds\7546b651\1\OpenShot\openshot-qt\freeze.py
<module 'cx_Freeze' from 'C:\\msys32\\mingw32\\lib\\python3.7\\site-packages\\cx_Freeze\\__init__.py'>
Copying modules to openshot_qt directory: C:\Users\Administrator\builds\7546b651\1\OpenShot\openshot-qt\openshot_qt
Loaded modules from openshot_qt directory: C:\Users\Administrator\builds\7546b651\1\OpenShot\openshot-qt\openshot_qt
running build
running build_exe
creating directory build\exe.mingw-3.7
copying C:\msys32\mingw32\lib\python3.7\site-packages\cx_Freeze\bases\Win32GUI.exe -> build\exe.mingw-3.7\openshot-qt
copying C:\Windows\system32\msvcrt.dll -> build\exe.mingw-3.7\msvcrt.dll
copying C:\msys32\mingw32\bin\libpython3.7m.dll -> build\exe.mingw-3.7\libpython3.7m.dll
copying C:\msys32\mingw32\bin\libwinpthread-1.dll -> build\exe.mingw-3.7\libwinpthread-1.dll
copying C:\msys32\mingw32\bin\libgcc_s_dw2-1.dll -> build\exe.mingw-3.7\libgcc_s_dw2-1.dll
error: [WinError 2] The system cannot find the file specified: 'build\\exe.mingw-3.7\\openshot-qt'
```

**Comment by ferdnyc** [comment]
> Ahh, all 3 build servers failed on this one:
> 
> Linux & Mac Error:
> 
> `<module 'cx_Freeze' from '/usr/local/lib/python3.4/dist-packages/`
> <code><b>cx_Freeze-4.3.4</b>-py3.4-linux-x86_64.egg/cx_Freeze/__init__.py'></code>

Wull... that explains _that_! Holy ancient cx_Freeze, Batman!

**Pull request merged**
