### PR TITLE
Implement interlace export

### PR DESCRIPTION
**Pull request by eisneinechse**
So far only an export in an mov container of an mpeg2 encoded clip works.
Further work is needed.

### CODE REVIEW

**Comment by SuslikV** [comment]
For what?

**Comment by eisneinechse** [comment]
This should fix 
https://github.com/OpenShot/openshot-qt/issues/2922

**Comment by SuslikV** [comment]
Isn't better to remove this feature completely? Someone said that there is 20 years of XXI century already gone.

**Comment by eisneinechse** [comment]
Short answer: No.
Longer:
There is even someone that wants it and we said it is there. We are no multinational company that screws people by selling them things and then delivering a subset.
We could of course streamline everything a little more, only export mpeg2 in a mov container with 720p at 24 fps ; that would make thing so much easier. And while we're at it let's ban the wheel, old technology.

**Comment by eisneinechse** [comment]
@ferdnyc This would be the interlace support we promised a long time ago.

**Comment by jonoomph** [comment]
LGTM

**Pull request merged**
