### PR TITLE
WIP: Attempting to open a recent project which has moved will no longer fail silently.

### PR DESCRIPTION
**Pull request by bnieuwveld**
OpenShot will also offer to remove the missing file from the Recent Projects menu.

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
Resolves (the long over-due) issue #293. :)

Awesome!

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc: I had the following suggestions regarding this PR, on slack. I thought perhaps you'd have some more input.

>The pop up doesn't give any explanation, which I think might be necessary. "Perhaps it has been moved or deleted?" would have been great. I wonder if you could put in a small check-box (with smaller fonts) the could be checked to remove the project from the recent-files list and only have [okay] button in the pop-up box. I am afraid the current one might be a little bit confusing to many users as often they are only used to clicking 'yes' instead of actually reading the message. Just a thought.

Basically, what I proposed was this:

**Could not find project *%s*. Perhaps it has been moved or deleted.**
- [ ] Remove *%s* from Recent Projects menu
                                                                                               [OKAY]

Sorry, I couldn't markdown it properly. But I hope you understand.

Any suggestions?

I think the dialogue should also offer to browse for the moved project file, though... implied by the issue mentioned above.

**Comment by ferdnyc** [comment]
As always, I think looking at other software is wise.

Here's how Audacity handles a missing Recent file:
image
Blender also displays an error message (not in a dialog, just as a transient popup that doesn't need to be confirmed) and removes the file from the recent list.

GIMP, OTOH, displays a "Could not open file" error in its messages panel, but leaves the file in the list. (GIMP's interface is terrible, though, so we shouldn't be looking to emulate it.)

I'd be most curious how software like Photoshop or Final Cut handles this, unfortunately right now I don't have access to any of those to test.

My instinct says that just removing the file from the list, automatically and without asking the user for permission, is probably the right move. A bad path in the recent list isn't really of any use to anyone. Either the file's been deleted, in which case no need to keep it around, or it's been moved to a new location, and when they open it from that other location it'll get added back to the list. But pruning bad paths from the list leaves more room to keep a list of _good_ paths, since slots on the Recent list are limited.

**Comment by ferdnyc** [comment]
> A bad path in the recent list isn't really of any use to anyone. Either the file's been deleted, in which case no need to keep it around, or it's been moved to a new location, and when they open it from that other location it'll get added back to the list.

I suppose technically a third possibility exists, that the file is merely _temporarily_ offline (like, on removable media) and might return at some later date. But, while I had to mention it for completeness' sake, I really don't feel like that's a common enough situation to design around.

**Comment by DylanC** [comment]
@bnieuwveld Do you want to rebase this on the develop branch? Will probably be needed before we could merge.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'ain, this is still a work in progress. Work is still to be done regarding the cleanup of recent files and stuff. Perhaps we need to wait a little longer...

**Comment by bnieuwveld** [comment]
@DylanC @peanutbutterandcrackers - Yes, I've been out of action for quite a few weeks, so this definitely needs a look with some fresh eyes. Rebasing the changes would be a good idea though.

**Comment by ferdnyc** [comment]
@peanutbutterandcrackers wrote:
> I think the dialogue should also offer to browse for the moved project file, though... implied by the issue mentioned above.

I would caution against this, only because it makes a lot more assumptions than you might think about the user's intentions and needs.
1. We don't _know_ the file was moved. 
   1. It could've been deleted, in which case there's nothing to browse for.
   1. It could've been renamed, in which case browsing for _that_ filename specifically won't work, so we'd just have to trigger an Open Project...
   1. It could be on an unmounted drive or disconnected network share, in which case they'll need to switch out of OpenShot and make it accessible before they can open it.
   1. They might've just accidentally clicked the wrong entry in the Recent list, and need to click a different one instead.
1. Not all users load project files through the application's browser. The user may prefer to quit OpenShot, use the Explorer/Finder/etc to browse for (or even _search_ for) the project file, and double-click it to relaunch OpenShot. Forcing them into the built-in file browser isn't helpful to those people.
1. If we're just triggering a general Open Project... browse (see 1.2), there's no real benefit to the user by asking if they want to do that. For users who _do_ want to do that, the Open Project toolbar button requires exactly the same 1 clicks as a "Yes" button in a dialog offering to browse. But if they _don't_ want to do that, then we're getting in their way if we make them click "No" on that same dialog to escape our over-"helping".

**Comment by bnieuwveld** [comment]
@peanutbutterandcrackers @ferdnyc - Where did we ever land on this one? My immediate thought would be a message box offering to either browse for the file (though, personally, I'd basically never do this), or remove it from the Recent Projects menu - at least that way it gives the user a choice. However, it might be testing my Qt skills...

**Comment by speedytechdev** [comment]
Any devs on I need help ASAP please

**Comment by ferdnyc** [comment]
> Any devs on I need help ASAP please

Someone else's unrelated PR is not a help forum. If you're having an issue, please [open a new Issue](https://github.com/OpenShot/openshot-qt/issues/new/choose). The project Issues are also not a help forum, so you need to describe your problem completely, not post "I need help". Nobody's going to help with whatever it is you need if they have to drag it out of you first.

**Comment by speedytechdev** [comment]
I am support and this is the only place I could find help. Everyone is reporting that Openshot is crashing and I don't know what to do. Please help.

**Comment by ferdnyc** [comment]
> I am support and this is the only place I could find help. Everyone is reporting that Openshot is crashing and I don't know what to do. Please help.

I told you how to get help. Please do not comment on this PR with unrelated issues again.

**Comment by peanutbutterandcrackers** [comment]
I agree (or rather, can't disagree) with @ferdnyc (after reading his arguments).

**Comment by bnieuwveld** [comment]
> If we wanted to show a message when removing an inaccessible Recents entry

...which I think we do, because a lack of any sort of feedback just doesn't feel right to me. (But I'm happy to hear any disagreements to this!)

> OpenShot's sadly-underused status line would seem like a reasonable place

True, I forgot about the status bar - and agree that it seems like a fitting use for it. Once I make the enhancement (and given the age of this one!), I will open a new PR and close out this one.

**Comment by peanutbutterandcrackers** [comment]
Once your new PR is submitted, we can test it out and give feedbacks. All the very best! :+1: :)

**Comment by peanutbutterandcrackers** [comment]
Well, we can always go back to either [this](https://user-images.githubusercontent.com/538020/40578757-bd0da184-60e7-11e8-8247-2249eff91545.png) or checked-by-default radio button - [this](https://github.com/OpenShot/openshot-qt/pull/1605#issuecomment-391225459) if the status bar idea - alone - doesn't feel quite right to you (both mentioned above).

**Comment by bnieuwveld** [comment]
Superseded by #2202

**Pull request closed without merging**
