### PR TITLE
Unify the getDocks searching algorithm

### PR DESCRIPTION
**Pull request by SuslikV**
Just found this in attempt to add new dock (simple curve editor or viewer for the animation keys).

### CODE REVIEW

**Comment by ferdnyc** [comment]
@SuslikV 

This won't work. Problem is, the Tutorial popup is a dock widget, which shouldn't be included in the `getDocks()` list when other parts of the `main_window.py` code request it. (The couple of functions that iterate over `self.findChildren(QDockWidget)` **should** include the tutorial popup, though, if it also matches the other criteria.)

**Comment by ferdnyc** [comment]
If you're adding a new dock (which sounds awesome, BTW) best thing is to just add it to the `getDocks` list.

**Comment by SuslikV** [comment]
Where?

OpenShot_all_docks_panes

**Comment by ferdnyc** [comment]
Here:

https://github.com/OpenShot/openshot-qt/blob/4431bd5c0af4ca705b4e958c193513be749e6bf3/src/windows/ui/main-window.ui#L387-L473

It's disabled+hidden except when in use, to keep it off that list.

(Though I assume that, when the tutorial _IS_ visible, it would appear.)

**Comment by SuslikV** [comment]
I only found that the tutorial window hides when switching from Simple UI to Advanced with this change. I will revert my changes.

Anyway, I wish to modify comment that describes the _getDocks()_
from:
`""" Get a list of all dockable widgets """`
to:
`""" Get a list of some dockable widgets """`
because the Tutorial dock lies in Qt::NoDockWidgetArea (not main window) and thus isn't listed on the screenshot.

**Comment by SuslikV** [comment]
It should work as intended. So updated code again to exclude Tutorial from the manipulations.

I want to add dock that lies in area of main window but not available until user's explicitly request.

**Comment by SuslikV** [comment]
The mentioned curve editor tool: https://github.com/OpenShot/openshot-qt/pull/3084

**Comment by SuslikV** [comment]
And it's not "work in progress" but "complete".

**Comment by jonoomph** [comment]
LGTM!

**Pull request merged**
