### PR TITLE
Appdata updates

### PR DESCRIPTION
**Pull request by ferdnyc**
Hey all. I've been pressed into service as the OpenShot package maintainer for Fedora Rpmfusion. (I don't know if that's _irony_, but it's definitely something.) So, in the interest of simplifying things on my end, I wanted to try and send some of the modifications we've been making back upstream.

This set of commits is all about the AppData file. We've been packaging one that we generated ourselves, mostly from our existing RPM package metadata. It had almost nothing in common with the one in the tree, so I went through and reconcile them both. These commits represent the diffs on your end. (I've already merged the updates to my end.)

Purely YMMV, I just thought I'd offer up the changes. The commit messages contain rationale / explanation for each individual edit, at a fairly fine-grained level.

### CODE REVIEW

**Comment by DylanC** [comment]
> Hey all. I've been pressed into service as the OpenShot package maintainer for Fedora Rpmfusion. (I don't know if that's irony, but it's definitely something.)

I found this really funny. Probably more than I should have. 😆 Umm, welcome back I guess! 😄 I'd be happy to merge this one.

**Comment by DylanC** [comment]
@ferdnyc - Merged this in and the icon one. (Good sir)

**Comment by ferdnyc** [comment]
> I found this really funny. Probably more than I should have.  Umm, welcome back I guess! 

As I mentioned when I agreed to take it on, I'll be supporting a bunch of my _own_ code in the next release, as it turns out, so... :laughing:

**Comment by peanutbutterandcrackers** [comment]
So glad the awesome @ferdnyc is back. Welcome back, good sir! :)

**Comment by ferdnyc** [comment]
> So glad the awesome @ferdnyc is back.

That is an overstatement, I would say. 

I'm handling OpenShot in a _support_ capacity as the rpmfusion package maintainer, and may contribute patches or file issues as they relate to our OpenShot package or which OpenShot users on Fedora / CentOS have reported to us. But I still don't have any plans to be doing additional development on OpenShot itself.

Still, it's always nice to be recognized. :wink: Good to "see" all you, as well.

**Comment by DylanC** [comment]
@ferdnyc - Maybe some time in the future you can chime in again (PR wise). From my understanding hardware acceleration is the focus atm but after that Travis CI is coming our way! :)

**Comment by peanutbutterandcrackers** [comment]
Even though this is really late: No, it wasn't an over statement. (Yeah, going through truck load of forum emails these days)

**Comment by ferdnyc** [comment]
> Even though this is really late: No, it wasn't an over statement. (Yeah, going through truck load of forum emails these days)

I guess, but I've also been filing bugs over at the new [Cinelerra-GG](https://www.cinelerra-gg.org/) bug tracker related to our packaging of _that_ editor, for which I'm also the maintainer. So I suppose this is the part where I confess: OpenShot, I've been cheating on you?

**Comment by peanutbutterandcrackers** [comment]
No!!!!!!!!!!!!!!!!!!!!!!!!!

Haha :laughing: 

Well, as long as it is not Lightworks or some other proprietary software that you are helping out with (which, we wouldn't have to worry seeing that you don't do flatpaks) it's all right. :smile: 

Thank you, BTW, for notifying about Cinelerra-GG. That's great. I think I'll check it out, myself. The only thing I do not understand is, what does `GG` even stand for?
They should also probably add themselves in the [wikipedia page](https://en.wikipedia.org/wiki/Cinelerra#Community_version). :)

**Comment by ferdnyc** [comment]
> Thank you, BTW, for notifying about Cinelerra-GG. That's great. I think I'll check it out, myself. The only thing I do not understand is, what does `GG` even stand for?

"goodguy", the username of the author. There's a whole fork drama I choose not to pay any attention to, but suffice it to say that Cinelerra-GG is distinct from both Cinelerra-CV (the Community Version) and Cinelerra-HV (Heroine Virtual, the original authors).

> They should also probably add themselves in the [wikipedia page](https://en.wikipedia.org/wiki/Cinelerra#Community_version). :)

Nobody should _**EVER**_ add _themselves_ to any Wikipedia anything, as it's a clear conflict of interest for involved parties to be writing about themselves in encyclopedia contact. Users have been banned from Wikipedia for far less.

Even I could never edit https://en.wikipedia.org/wiki/OpenShot as I'm too involved in the project to write from a [NPOV](https://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view).

**Pull request merged**
