### PR TITLE
WIP: Stopped Progress Got Stuck- Setup toggle buttons for timeline actions

### PR DESCRIPTION
**Pull request by speedytechdev**
This makes it easier for people to work on video only or only work on audio. (More information coming soon)

### CODE REVIEW

**Comment by speedytechdev** [comment]
What would be the best way to toggle the audio and video. For example, set the screen black when the video is toggled. Some help would be great thanks.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I just realized, this might be a possible duplicate of #1993? It wouldn't be highly beneficial to have two contributors working on the same thing at the same time, differently, would it?

**Comment by speedytechdev** [comment]
@peanutbutterandcrackers I saw the pull request that Dylan made and I saw it was out of date with the main branch so I thought I might work on it. So yes working on it might mean we can get it out sooner.

**Comment by speedytechdev** [comment]
I have a problem and I am not sure how to fix it I was wondering if anyone could help. So I have set up the toggle buttons but the problem is if I turn off audio for one track it will do it on all the tracks. Is there anyone I can fix this?

**Comment by jonoomph** [comment]
This looks like a WIP at the moment, so I updated the title.

**Comment by DylanC** [comment]
@jonoomph - This PR won't be updated any time soon I reckon but it is a much requested feature from the Openshot 1.x series. Hopefully someone with the right knowledge can implement. 😉

**Pull request closed without merging**
