### PR TITLE
Newline in blender titles

### LINKED ISSUE #4541: Star Wars animated title does not accept "\n" character, generating a single line title
**Describe the bug**
Star Wars animated title shows "\n" instead of doing a new line

**Steps to reproduce the behavior:**
1. Launch opehshot
2. Select "Animated Title"
3. Select the star wars intro like animated title generator
4. Move the slider preview to a frame near 100

**Expected behavior**
A two line blue text should appear, but instead you view a single line  with "\n" inside.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Linux-5.11.0-40-generic-x86_64-with-Ubuntu-20.04-focal
- Processor: x86_64
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['es-ES']
- LANG Environment Variable: es_ES.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step (Daily build interface looks too bad to be usable in my computer)

**Additional info**
Tried in several computers with both Appimage and Flatpak versions, and several Blender versions (2.80 to 2.95).

Captura de pantalla de 2021-11-16 12-00-11

### PR DESCRIPTION
**Pull request by JacksonRG**
I'm not sure what changed, Blender or Qt's handling of special characters, But I believe this will be clearer to the user, as they can create new lines as they might in most text editors.
spacemoviePrevious
Pictured above: The line breaks working incorrectly
spacemovieUpdated
Pictured above: Changing to multi-line text fields, replacing `\n` with visible carriage returns.

### CODE REVIEW

**Comment by jonoomph** [comment]
LGTM!

**Comment by JacksonRG** [comment]
@jonoomph While I'm editing it, How do I re-export the blend? I'm looking to pull the scrolling text back a bit to prevent this from happening.
Frame1Spacemovie

**Comment by jonoomph** [comment]
@JacksonRG You can drag the "Frame Slider" to change which frame is being previewed. You can also click the "Refresh" button at any time to re-render the current frame. Once you start exporting an animation though, there is no way to make further adjustments. You would need to redo the entire animation again.

**Comment by JacksonRG** [comment]
@jonoomph 
Is there a way to change the `.blend` file it's rendering? So I can move the Episode title, and main text out of view of the camera?

**Comment by jonoomph** [comment]
The *.blend files can be edited using Blender 2.8+

**Comment by JacksonRG** [comment]
Figured out why I was getting [that](https://github.com/OpenShot/openshot-qt/pull/4550#issuecomment-977309294) bug! The `.blend` file is fine. I just had a weird aspect ratio.

I might take on adapting the position of the scrolling text to the video profile. But that's a very separate issue.

**Comment by JacksonRG** [comment]
Rebasing messed this up. See PR #4597

**Pull request closed without merging**
