### PR TITLE
[WIP] Check in changes which alter the preview window to apply the proper a…

### PR DESCRIPTION
**Pull request by N3WWN**
…spect ratio.  Now, each time a project is loaded, the Profile selection dialog is opened in order for the user to verify the selected profile.  Upon closing of the Profile dialog, the preview window aspect ratio is updated.  Modified SetAspectRatio() in video_widget.py instead of creating a new function since the existing function does not appear to be used anywhere.

I worked this specifically for https://github.com/OpenShot/openshot-qt/issues/1402, but this PR should (partially or completely) resolve all of : 

https://github.com/OpenShot/openshot-qt/issues/456
https://github.com/OpenShot/openshot-qt/issues/731
https://github.com/OpenShot/openshot-qt/issues/835
https://github.com/OpenShot/openshot-qt/issues/1093 (item # 4)
https://github.com/OpenShot/openshot-qt/issues/1144
https://github.com/OpenShot/openshot-qt/issues/1402

### CODE REVIEW

**Comment by DylanC** [comment]
@N3WWN - Awesome, thanks! :) Might take care of many issues at once.

**Comment by ferdnyc** [comment]
> Now, each time a project is loaded, the Profile selection dialog is opened in order for the user to verify the selected profile.

If I'm interpreting that correctly (and apologies if I'm not), the Profile dialog will be displayed _every_ time a project file is opened? To what purpose?

When I save a project file with a profile I've selected... well, then the whole _purpose_ of storing it there is so that I **don't** have to select that information again. Certainly not every time I load the project! Why do I need to keep "verifying" what I've already selected? (And if I _want_ to verify the profile selection, well, the current profile is displayed in the titlebar of the main OpenShot window.

If that's not enough for people, and they're ending up working under the wrong profile because they're not reading the window title (or maybe they don't see titlebars, because they're fullscreened or whatever), then why not move the profile selector _itself_ into the main interface? 

That `Profile:` dropdown list from the Choose Profile dialog window (the only interactive element there, other than the Close button) could be placed **directly** on OpenShot's toolbar, in place of the current Choose Profile button. (Though I think it'd be better moved to the right, after all the other buttons — or even onto its own, separate, movable toolbar segment.)

That way, if the user wants to verify the selected Profile, they just look at what's selected in the dropdown list. If they want to select a different profile, they just _open_ the list.

I'd prefer that, myself, over having that already-kind-of-pointless little one-widget dialog window being unnecessarily thrown in front of me all the time. No?

(The Choose Profile dialog could still be retained in the interface, as an alternate "advanced mode" profile selector. It does break out useful info like the selected profile's dimensions, frame-rate, aspect ratio, and field ordering details, if the user wants to examine those in detail.)

**Comment by N3WWN** [comment]
@ferdnyc I have to admit a bit of lack of understanding in how OpenShot works which led to this "feature".  😕  I was unable to determine how to alter the project profile properties without going through this dialog.  I tried many, many potential avenues to do it, but could not quite get it to work properly.  

I figured that someone would see this, know exactly what the code is trying to do, and go, "oh, you have to do it this way".  😁  

If you can point me in the right direction on how to adjust the project profile settings without going through this dialog, I'd love to hear it and I'll update my PR to include the change.

This is a "getting my feet wet" contribution for OpenShot.  My intention was not to be this kludgy... as I mentioned, I figured I'd get called out on it during review and I'm glad you've done that.

**Comment by ferdnyc** [comment]
Gotcha. Well, that _should_ be solvable without opening the dialog, if necessary. The project loader already sets the profile (and causes display updates like setting the window title), it could repaint the video preview too.

But there's a larger issue, in that resizing the preview doesn't appear to work as intended. It shapes the preview to the output aspect ratio, yes, but unfortunately that comes at the expense of previewing what will actually be output.

In OpenShot 2.4.1, if I select the NTSC profile and import 16:9 video, the video will be shown at 16:9 in the preview:

screenshot from 2018-03-26 19-26-24

That _seems_ wrong, but it's arguably **correct** because with the default Best Fit scaling, the video will be output letterboxed. So the resulting video will be exactly as shown, except it will have black bars on the top and bottom.

With these changes, though, the preview is resized to 4:3, which previews the 16:9 video distorted to 4:3 aspect, despite the fact that it will _actually_ be output letterboxed with no distortion:

screenshot from 2018-03-26 19-27-30

By the same token, if I reimport my exported 4:3 video, the default OpenShot preview shows it with bars on all four sides:

screenshot from 2018-03-26 19-26-14

Again, weird but arguably **correct** — or, at least, correct aspect ratio — since the output video will _actually_ be 4:3, with the preview's left- and right-side bars chopped off.

But with these changes, the preview doesn't match the output video here, either:

screenshot from 2018-03-26 19-32-09

I think having the preview window reflect the output aspect precisely would be a good thing, but it doesn't appear that resizing the widget is the way to achieve that unfortunately. The preview renderer appears to expect the default 16:9-aspect preview image, and generates previews already-formatted to fit that size. Resizing the widget only distorts the preview.

**Comment by jonoomph** [comment]
I'm worried about merging this one, due to the forcing a profile dialog on every project. We should probably come up with a better or less obvious way to accomplish this same thing.

**Comment by ferdnyc** [comment]
@jonoomph : You know the preview code better than any of us, can you offer any insight on how intrinsic the locked 16:9 aspect ratio is? In my testing of this patch, unfortunately it seemed like resizing the widget resulted in distorted previews, since the video was still 16:9 regardless of output profile (and then became distorted by the resizing).

AFAICT the preview renderer expects a fixed 16:9 preview viewport, and ignores the target aspect entirely. (It previews 16:9 video full-frame even when it's going to be output at 4:3 with letterboxing, for instance.) So I'm wondering how deeply that fixed preview aspect is baked into the code, and where it'd need to be changed to make non-16:9 previews possible. (With the eventual goal being to conform the preview's aspect to the selected output profile.) Any insights you can offer?

**Comment by DylanC** [comment]
@N3WWN - Closing since this relates to master and not develop. Please re-submit if you plan to get this in. Thanks.

**Pull request closed without merging**
