### PR TITLE
Add preset xml file for chromebook target

### PR DESCRIPTION
**Pull request by DylanC**
This should take care of #1329

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
:smile: 
25vxez

**Comment by ferdnyc** [comment]
The standard/default Chromebook samplerate is 44.1kHz, not 48kHz? That's surprising and unfortunate.

**Comment by DylanC** [comment]
@ferdnyc - We should be able to still update this anyway.

**Comment by DylanC** [comment]
@ferdnyc - I found this:
https://developer.chrome.com/native-client/devguide/coding/audio

This page has the following information:
- sample rate: 44,100 Hz or 48,000 Hz
- bit depth: 16
- channels: 2 (stereo)

Should this PR be updated to 48Hz?

**Comment by ferdnyc** [comment]
I guess not, since (now that I've checked) **all** of the existing presets use 44.1kHz except for `avchd.xml`, `dvd_pal.xml`, and `dvd_ntsc.html`. I've gotten used to thinking of 48kHz as sort of "standard video rate", since it's not only what DVD uses, but AFAIK all broadcast/cable is sampled at that rate as well (if not higher). But it makes sense to follow OpenShot convention, which seems to be 44.1kHz. If that were going to be changed, probably better to change the whole preset collection (or most of it) all at once.

**Comment by ferdnyc** [comment]
Although, I noticed that even the two youtube presets use 44.1kHz, when [YouTube's recommended settings article](https://support.google.com/youtube/answer/1722171) explicitly calls for either 48kHz or 96kHz audio. So, maybe it's worth considering an audit of the presets' samplerate settings.

**Comment by DylanC** [comment]
@ferdnyc - Yes, I think its worth some more investigation and a review of our current sample rates.

**Comment by jonoomph** [comment]
Merged, thanks! I agree, we probably need to update a bunch of these presets, and add some other common missing ones.

**Pull request merged**
