### PR TITLE
Icon/pointer fixes

### PR DESCRIPTION
**Pull request by ferdnyc**
Two changes to the application chrome:

1. Switch the "Jump to Start/End" icons to `media-skip-forward`/`-backward`. The icons previously being used were `go-first` and `go-last` from the navigation set, which are also used for the marker-skipping controls on the timeline toolbar. Displaying identical icons that have two completely different meanings leads to confusion. (Addresses #920 .)
    
    So in Gnome Shell on Fedora (where OpenShot uses platform icons), the controls look like this:    
    screenshot from 2018-03-14 06-44-50

1. I re-drew the razor-tool cursor image `razor_line_with_razor` in Inkscape as an SVG, then exported the PNG from there. I found that with the previous cursor, the dotted blue line was difficult to make out against the application's dark theme.The new one's lines are a bit cleaner, it's slightly taller, and it uses a _much_ lighter blue for the dotted line. (It's practically white, I may have overdone it a bit).
    
    Before & After:
    openshot-oldrazor
    openshot-newrazor
    (It's hard to see but the knife part is outlined in dark gray, so it doesn't disappear against light colors.)

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
Awesome!

**Comment by jonoomph** [comment]
I'm a bit worried this might result in missing icons on Windows and Mac, so we'll need to do some testing once this version is done building installers.

**Comment by jonoomph** [comment]
Oops, hit enter too quick, haha. Thanks again for a great PR!!!

**Comment by ferdnyc** [comment]
> I'm a bit worried this might result in missing icons on Windows and Mac, so we'll need to do some testing once this version is done building installers.

That's a good point, and certainly something I didn't (couldn't) test, but I'm _hoping_ it'll be OK. The icon files were already present in the source tree (`src/images/Humanity/actions/16/media-skip-{backwards,forwards}.svg`), _and_ were already listed in `src/images/openshot.qrc`, so it was just a matter of saying "Hey, use these!" in the UI file. And, certainly, `media-skip-*` are pretty universally-standard icons, every bit as much as `go-prev` and `go-next`. But I imagine it would be `openshot.qrc` that the build servers would be working, off to determine the icon file set to package (and/or actual usage in the source code), yes?

**Comment by peanutbutterandcrackers** [comment]
OpenShot certainly looks a *lot* better with this PR merged, though. Awesome work, @ferdnyc!

I hope this will be all right on Windows and Macs too...

**Pull request merged**
