### PR TITLE
Add confirmation dialog when canceling export

### PR DESCRIPTION
**Pull request by SuslikV**
Just fully localized temporary solution that targets this small request: https://github.com/OpenShot/openshot-qt/issues/3190#issuecomment-576935708

Export paused until decision taken.

Is it works for all systems? I can only test it in Windows.

### CODE REVIEW

**Comment by ferdnyc** [comment]
Works well, thanks! I pushed a commit with a couple of tweaks:
- Change title to "Export Video", since we already have a translation for that string
- Use `QMessageBox.question()` and the `QMessageBox.No | QMessageBox.Yes` convenience objects, which automatically decorates the "No" and "Yes" buttons with icons, uses Qt built-in translations, and adds accelerator keys (localized) for each response.

Merging.

**Comment by SuslikV** [comment]
In this short notation the default button is missing ("No"):
```
QMessageBox.No | QMessageBox.Yes, QMessageBox.No)
```

**Comment by ferdnyc** [comment]
> In this short notation the default button is missing ("No"):

Not missing, just unspecified. (The default value, `QMessageBox::NoButton`, is used.) [Which means](https://doc.qt.io/qt-5/qmessagebox.html#question):
> If _defaultButton_ is [`QMessageBox::NoButton`](https://doc.qt.io/qt-5/qmessagebox.html#StandardButton-enum), QMessageBox chooses a suitable default automatically.

(It picks "No".)

**Comment by SuslikV** [comment]
> (It picks "No".)

^_^ It's for you only. When I hit <kbd>Enter</kbd> twice - export terminates.

**Pull request merged**
