### PR TITLE
Avoid changing main window state during tutorial

### PR DESCRIPTION
**Pull request by ferdnyc**
The tutorial's event filter was using `window.showNormal()` to activate the main OpenShot window, which explicitly forces the window into a normal (as opposed to minimized/maximized/fullscreened) state. This is disconcerting for users who wish to keep the application in the state they've selected. Switch to `window.show()` which respects existing state.

Fixes: #307, #1036, #1447, probably more duplicates

### CODE REVIEW

**Comment by ferdnyc** [comment]
I may push more fixes into this branch if I can ferret out the issues with tutorial window(s) state/placement and not accepting input, which users of certain window managers have reported. Those appear to also be related to the event filter, given that a common thread among many of those reports is that they describe the tutorial popup as "flickering". (I don't see any issues under Gnome Shell, which makes debugging them a bit trickier.) If I come up with anything I'll update this PR accordingly. 
Ref: #1080, #1264, #1555, #1623

**Comment by peanutbutterandcrackers** [comment]
I can not stress how happy I am about this improvement! This would have been the first impression for the users. And now this is fixed. Awesome. I hope you do fix the flickering-s and all. This is awesome! Thank you! This one was long overdue, too! Many many many thanks!

**Comment by ferdnyc** [comment]
> P. P. S: Perhaps you might want to delete the branches that have already been merged, good sir? git fetch ferd is showing too many branches. :D

For the most part I do! Believe it or not _most_ of the remaining ones are active (or at least contain unmerged code worth holding on to). There was one I'd missed, `title-svg`, for my most recent merged PR. That's now gone, and I also deleted the unimaginatively named `testbranch` since I honestly have no idea what that was even about and there was no useful code on it.

You will need to do a `git fetch --prune` or `git pull --prune` in order for the deletions to be propagated locally, though. Otherwise, you'll still be seeing deleted branches. The pruned list should look like this:

```console
$ git branch -r |grep origin
  origin/HEAD -> origin/master
  origin/clip-resizing
  origin/docs-markup
  origin/effects-pane
  origin/master
  origin/menu-structure
  origin/samplerate
  origin/traceback
  origin/tutorial-fixes
  origin/widget-styling
  origin/zoom-tweaks
```

**Comment by peanutbutterandcrackers** [comment]
The `testbranch` has not yet been deleted. Perhaps you forgot to push your changes on to github?
Here's the output of `git branch -r | grep ferd`:
```
  ferd/clip-resizing
  ferd/docs-markup
  ferd/effects-pane
  ferd/master
  ferd/menu-structure
  ferd/samplerate
  ferd/testbranch
  ferd/traceback
  ferd/tutorial-fixes
  ferd/widget-styling
  ferd/zoom-tweaks
```

**Comment by ferdnyc** [comment]
> The testbranch has not yet been deleted. Perhaps you forgot to push your changes on to github?

Apparently local branch deletions won't be pushed on to the remote, even when they're remote-tracking branches. (`git branch -d -r origin/testbranch`) Blowing away the _remote_ branch requires an explicit `git push origin --delete testbranch`. So, now deleted-for-real.

**Comment by peanutbutterandcrackers** [comment]
I can confirm! It's been deleted. :)

**Comment by ferdnyc** [comment]
I just pushed a second commit 1b41150 into this branch which changes the way the tutorial popups are created and managed. I've tested it under Gnome Shell on Fedora 28, and under Windows 7, and it has no effects that I can discern on the tutorial. (That's a good thing, as the tutorial has been functioning fine on those platforms.) 

I'd like to get some feedback from those who were having #1555 / #1623 type problems with the tutorial windows not behaving with their window manager, to see if it fixes the problem for any of them.

**Comment by peanutbutterandcrackers** [comment]
I tested it on my buddy's Linux Mint 18.3 machine and it works just great.

However, I noticed two things, that perhaps could be improved? It's not an issue with your changes, though. It is the same way with upstream master.
screenshot at 2018-06-10 15-55-30
Is that how it should be working? I mean, could the tutorial window be a child or something? I'm sorry if I am asking for something impossible. Please excuse my ignorance.

Also, this:
screenshot at 2018-06-10 15-54-42
It seems the tutorial (correctly) assumes that the view is 'simple' view (it would launch automatically when OpenShot first starts, and the users advanced enough to change the program layout probably would not be interested in the tutorial). Could it be made layout-sensitive, though? So that the arrow would point at the right place? o.O

Wait, turns out, in 'simple view', properties tab isn't shown and so the tutorial just skips that part.

However, when it is in 'advanced view', the same issue (of wrongly pointed arrow) repeats with the effects tab. Here:
screenshot at 2018-06-10 16-07-44

Perhaps you can fix it, too? o.O

[Sorry if I'm asking for too much. I think I am.]

**Comment by peanutbutterandcrackers** [comment]
Sorry. I meant to say it works just great as before. There were no issues with the upstream/master branch and no issues with this one either.

Could that enhancement be made? That'd be awesome. lol

Hmm... I look forward to further commits. It'd be nice if this could be dropped with v2.4.2.

**Comment by ferdnyc** [comment]
> Could that enhancement be made?

Nope. I _never_ cared about the stupid tutorial, and I've already spent far more time than I care to on it.

> Hmm... I look forward to further commits. It'd be nice if this could be dropped with v2.4.2.

I thought we were in a code freeze for 2.4.2!?! **\*confused\***

Regardless, I'd hate to see this go into a release without feedback from people who were having actual issues. We don't know if it **works** yet. Getting it into daily builds would be great, certainly, as it would help with testing. But releasing with this would be extremely premature, without feedback from at least some of the people experiencing the issues I linked in my second comment above.

**Comment by peanutbutterandcrackers** [comment]
Haha. lol Okay.

Yes, we are in a code freeze; but the bugs from rc-1 are being dealt with. I thought it'd be nice if this could be dropped in as well.

Okay. I'll try to get Mr. Thomas's attention to this one - to get this into the daily builds, at the very least. :)

Thank you, nevertheless, @ferdnyc; you are indeed a brilliant programmer. :D

**Comment by DylanC** [comment]
@ferdnyc - Yes, I think we should hold off. @peanutbutterandcrackers - I know this would be a great change to get in but lets not risk causing some other issues by merging this in too soon. It definitely should go in but maybe for v2.4.3.

**Comment by peanutbutterandcrackers** [comment]
Hmm... all right, then. I'll try to hold my enthusiasm about this PR in, for now. :D

**Comment by jonoomph** [comment]
We are good with merges to develop, but it won't be merged into release (that is frozen) =)  Thanks. Hopefully now that it's merged into our daily develop builds, more people can test it.

**Comment by ferdnyc** [comment]
Perfect, thanks. If someone can ping me when the first build(s) with the change are downloadable, I'll try to solicit feedback from some of the issue reporters. (Or I'll just try to remember to check, like, tomorrow or whenever.)

**Comment by peanutbutterandcrackers** [comment]
It's already shipped in the PPAs, though. :)

**Comment by ferdnyc** [comment]
Hey, [that tweet](https://twitter.com/openshot/status/1007433962937933824) is your guys' call, but IMHO this is _not_ a change that calls for **widespread** testing, because we've already established that 90% of users won't see any differences at all. It's only users of certain _specific_ systems / desktop environments that this change is even targeted to, and who we need feedback from. For everyone else, this is _meant_ to be an invisible change.

Myself, I wouldn't want to field numerous, "other than the tutorial running in fullscreen, it's exactly the same as before" reports from users testing on systems where we already **know** that's the case. But if you're into that, cool...

**Comment by peanutbutterandcrackers** [comment]
Sorry... I am handling the twitter for OpenShot now. And I'm trying to adopt the gimp model - they let the users know about most of the changes happening. And because this is a visible change, I thought it'd be a good idea to notify the users. I don't think there'll be wide-spread testing. We don't have that many followers. I'm just trying to make OpenShot active on social media.

Do you want me to delete the tweet?

**Comment by ferdnyc** [comment]
`¯\_(ツ)_/¯` I've given my take on the issue, it's really up to you. I have no problems with the tweet, it just strikes me as unnecessary (and really overselling a nothing change).

**Comment by peanutbutterandcrackers** [comment]
I'll keep it then. It makes OpenShot look active on social media, at the very least. From next time onward, though, I'll be careful not to add the "anyone willing to test it?" part. That way, it'll be for of an informative tweet rather than an invitational one. Sorry for this one. Hehe :D

**Pull request merged**
