### PR TITLE
Add Fusion style to themes

### PR DESCRIPTION
**Pull request by SuslikV**
Inspired by: https://github.com/OpenShot/openshot-qt/issues/3325

### CODE REVIEW

**Comment by ferdnyc** [comment]
This makes total sense to me, in as much as it unifies our themes to display in the same style. But rather than adding a third theme option, I'm sort of more inclined to just fix "Humanity" (non-dark) so it also forces Fusion style the same way the dark version does. In fact, it feels like a bug/oversight that it **doesn't**. (Possibly a consequence of the light theme's overall neglect.)

On Linux with this change, "Humanity" and "Fusion" would be literally identical — er, fonts possibly excepted — because "Fusion" is the default style (which is why I couldn't see the #3325 issue originally). And on Windows, if the only difference between "Humanity" and "Fusion" right now is that one has broken/invisible splitters and the other doesn't, then why keep a broken "Humanity" around at all? It makes more sense to me that our themes always force the same style. Ditto macOS, at least to whatever extent "Humanity : Dark" is already successful in forcing its own app style on a Mac (a notoriously hard thing to do).

There's also the existing "No theme" option, which on Linux will again be the same as "Humanity" and/or "Fusion" except missing the font-size change. (So, even _more_ identical to "Fusion".) And right now on Windows, "No theme" is effectively "Humanity" without the font adjustment. So, if we change "Humanity" (non-dark) to force the Fusion style, then "No theme" will actually have a purpose on Windows, and "Humanity" will be consistent in light and dark versions.

**Comment by SuslikV** [comment]
Difference in fonts size is far more noticeable then you think:

Humatity (100% DPI screen, 1280x1024)
Openshot Humanity

Fusion (100% DPI screen, 1280x1024)
Openshot Fusion

And fore sake of comparison Humanity with Fusion set same as for the Dark theme (main menu has smaller letters):

<details>
  <summary>Click to expand</summary>

Humanity + Fusion (100% DPI screen, 1280x1024)
Openshot Humanity+Fusion

</details>

**Comment by MBB232** [comment]
> Difference in fonts size is far more noticeable then you think:

Clear difference in your screenshots. Is this a _purpose_ of the themes, to offer a larger font? Should one in particular be recommended for people with bad eye sight or large resolution small screens?

**Comment by SuslikV** [comment]
> Is this a _purpose_ of the themes, to offer a larger font? Should one in particular be recommended for people with bad eye sight or large resolution small screens?..

When I first time run the application it was my first thought too. But @ferdnyc said that it is just bug from the porting it to Windows. And fonts actually should be all same size (as No Theme), More over, there will be no visual difference between new Fusion and Humanity on linux :(

**Comment by MBB232** [comment]
> > Is this a _purpose_ of the themes, to offer a larger font? Should one in particular be recommended for people with bad eye sight or large resolution small screens?..
> 
> When I first time run the application it was my first thought too. But @ferdnyc said that it is just bug from the porting it to Windows. And fonts actually should be all same size (as No Theme), More over, there will be no visual difference between new Fusion and Humanity on linux :(

ok, no real need to document it then. 
Nor to make a feature request out of if it won't work the same on all platforms.

**Comment by SuslikV** [comment]
It is unknown if all Windows users already seeing this as a "feature". So, the linux variant of Humanity theme may be considered as bugged. Then PR is valid but linux has the bug...

**Comment by jonoomph** [comment]
Closing PR. While this obviously needs some fixing, it doesn't seem like this PR solves the root issue. Also, when we revist the themes, it would be great to extend theme support into the timeline (conditional CSS include perhaps)

**Pull request closed without merging**
