### PR TITLE
flexible time stretching

### PR DESCRIPTION
**Pull request by pauloord123**
Now Time has only some fixed stretching factors (2, 4, 8, ...x and 1/2, 1/4, 1/8, ..). 
For exact synchronising audio and video a free factor (e.g. 0.56) must be possible. Or stretching one track to the length of another track.

### CODE REVIEW

**Comment by peanutbutterandcrackers** [comment]
Hey there,

If I am not mistaken, you seem to have made your changes from off the 'master' branch and are now trying to push to 'develop' (or sth similar). Could you please go back, and sync your upstream to the latest changes and then make a branch off `develop` instead of `master` and apply the changes and then make a PR to be merged into OpenShot's develop branch? Could you please also increase the explanation so that it'll be a bit more clearer? Thank you for taking the time to improve OpenShot. We look forward to your future contributions as well. :)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Cap'n, care to look at his one, please?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I don't know what he is doing. I think he mean't to report an issue. @pauloord123  - Can you report an issue if you have something to report. Thanks.

**Comment by pauloord123** [comment]
Dylan,
I had a request, but i have solved the issue with ffmpeg and applescript. The problem was to get two independent tracks (one only video and one only audio) merged. If openshot was not so rigidly programed  for speed correction, it was a solution, now i have my own.
Sorry for the inconvenience,
Paul

Verstuurd vanaf ons iPadje

**Comment by DylanC** [comment]
@pauloord123 - No problem. Glad to hear you found a solution.

**Pull request closed without merging**
