### PR TITLE
Create INSTALL.txt

### PR DESCRIPTION
**Pull request by ballsystemlord**
This explains how to install openshot-qt.
Fortunately for your project, I'm very used to installing things from source.
It explains how to overcome the following errors:

% openshot-qt
Loaded modules from installed directory: /usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Sun Jun 13 22:20:18 2021
         app:INFO               Starting new session
         app:ERROR OpenShotApp::Import Error: libopenshot.so.19: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/openshot.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: libopenshot.so.19: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/local/lib/python3.5/dist-packages/openshot.py", line 21, in <module>
    _openshot = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/openshot.py", line 20, in swig_import_helper
    return importlib.import_module('_openshot')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libopenshot.so.19: cannot open shared object file: No such file or directory
         app:INFO             OpenShot's session ended
         app:INFO ================================================

% export LD_LIBRARY_PATH="/usr/local/lib"
% openshot-qt
Loaded modules from installed directory: /usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt
         app:INFO ------------------------------------------------
         app:INFO             Sun Jun 13 22:22:57 2021
         app:INFO               Starting new session
         app:ERROR OpenShotApp::Import Error: No module named 'zmq'
Traceback (most recent call last):
  File "/usr/local/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.5.1', 'gui_scripts', 'openshot-qt')()
  File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt/launch.py", line 97, in main
    app = OpenShotApp(argv)
  File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt/classes/app.py", line 72, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/local/lib/python3.5/dist-packages/openshot_qt-2.5.1-py3.5.egg/openshot_qt/classes/logger_libopenshot.py", line 33, in <module>
    import zmq
ImportError: No module named 'zmq'
         app:INFO             OpenShot's session ended
         app:INFO ================================================

### CODE REVIEW

**Comment by ferdnyc** [comment]
I'm *very* -1 on having _yet another_ piece of documentation outlining our install steps, when we already have:
* This [incredibly outdated wiki page](https://github.com/OpenShot/openshot-qt/wiki/Dependencies-for-OpenShot-Qt)
* [doc/installation.rst](doc/installation.rst) (OK, this one doesn't really cover installation at all, ironically.)
* [doc/developers.rst](doc/developers.rst)
* The part of [README.md](README.md) that deals with dependencies
* [libopenshot/INSTALL.md](https://github.com/OpenShot/libopenshot/blob/develop/INSTALL.md)
* The three install guides in [libopenshot/doc/](https://github.com/OpenShot/libopenshot/blob/develop/doc/) which deal with installation to Linux, Mac, and Windows systems specifically

...and (in part because there _are_ so many already), none of those documents quite matches any of the others. Adding one more will only worsen that problem.

As far as Python dependencies go, there are a _lot_ more than just pyzmq. And if we're going to list them, we should do it through a standard `requirements.txt` file. (We should really, really have a `requirements.txt` file.)

**Comment by ballsystemlord** [comment]
Ok, in order:
1a: Including it inside of the source dir has been common sense since time immemorial.
1b: As someone who didn't have internet at his house for many year, people need the installation file inside of the source repository.
1c: It doesn't explain all of the steps as to how to install openshot-qt.
2: As you said, an installation file that doesn't even cover the installation.
3a: People are not going to look in the developers.rst file for installation instructions.
3b: Considering that it's an rst file, it's meant to be read after being "compiled". That's why it's a markup file. Therefore, it makes no sense to use rst files for the installation instructions.
4: The readme includes only partial instructions.
5a: Who on earth would look at a library for installation instructions for a program??? That's not just weird, I've never heard of or seen it before in my life -- and I've seen some weird source repos.
5b: The installation of openshot-qt isn't covered in full inside of these documents.
6: See 5a and 5b.

My entire attempt here was to document the installation process. I'll happily abandon my changes in favor of an approach that documents how to install openshot-qt inside of the openshot-qt source repo. If it must be rst, fine, but at least give us the full instructions and place them where people will find them!

**Comment by jonoomph** [comment]
[Improve INSTALL.md instructions on all repositories and Wiki (w/ less duplication)](https://trello.com/c/Exam8s7u/89-improve-installmd-instructions-on-all-repositories-and-wiki-w-less-duplication)

**Comment by jonoomph** [comment]
Thanks so much for the work on this one, but as mentioned in the comments, I think we need a more comprehensive approach to INSTALL instructions, which has less duplication across our projects and Wikis.

**Comment by jonoomph** [comment]
Closing this at the moment, but tracking this issue in our Trello board to be re-visited very soon.

**Pull request closed without merging**
