### PR TITLE
Fix "Add track" action (toolbar icon, keyboard shortcut)

### LINKED ISSUE #3696: "Add Track" Timeline menu icon has no effect
2.5.1-dev2 Win10
Above the Timeline are some icons; the left one is a plus, which says "Add Track" when hovered over. It's next to "Snapping Enable."

It does not add a track, or do anything else.

I've spent 45 mins searching for an existing issue on this - sorry if I've missed it. These icons are undocumented, so I guess it's possible this works in an unexpected way, but I can't imagine what it is, if so.

### PR DESCRIPTION
**Pull request by ferdnyc**
Seems I tried to get too clever with Python iterators.

Also squashes a bug I hit in the JS `updateLayerIndex` implementation.

Fixes #3696

### CODE REVIEW

**Comment by ferdnyc** [comment]
Hrm. Travis is doing that thing again where one of the two builds for the PR goes out to lunch and never comes back.

If I visit the Travis CI website, the job is completed and successful. But the Github Actions interface never notices, and there's no way I can see to tell it, "Check again." (In fact, if I forcibly restart the job, the same thing will happen again.)

Adding a commit to the PR nearly always fixes it, but that's a pain and we shouldn't have to. I need to open a bug report with them.

**Comment by ferdnyc** [comment]
I only just today noticed a critical data point about this problem, and have [documented it to the Travis support forum](https://travis-ci.community/t/duplicate-job-attempts-for-pr-builds-causing-queued-build-created-problems/9776). Now we wait...

**Comment by ferdnyc** [comment]
I also noticed that my fork still had an old Webhook from travis-ci.org installed on it, so I removed that. I'm wondering if maybe the same thing might be true on the OpenShot repo end. Time to email @jonoomph ...

**Comment by ferdnyc** [comment]
Stuffed in a totally unrelated, but good-to-have, change to unstick the build.

**Comment by jonoomph** [comment]
LGTM! Merge away!

**Pull request merged**
