### PR TITLE
Update Blender scripts to change align to align_x

### PR DESCRIPTION
**Pull request by mixedbredie**
The Blender Python API (https://www.blender.org/api/blender_python_api_2_78a_release/bpy.types.TextCurve.html?highlight=align_x#bpy.types.TextCurve.align_x) has been updated and the Python attribute in TextCurve has changed from `align` to `align_x`.  I have updated the scripts to reflect this change.

I'm running the latest OpenShot 2.1 and Blender 2.78a on both Windows and Linux Mint 18 and have had to make the changes to both sets of scripts in order to get Blender to generate the animated titles. The updated scripts work perfectly. There are a number of issues logged (#396, #379) that I think this will fix.

### CODE REVIEW

**Comment by janagyjr** [comment]
I have tried the manual fix and I have a no go, will this for sure work in a new build of OpenShot?

**Comment by mixedbredie** [comment]
Are you still getting error message when you try to call Blender from OpenShot to make an animated title?

**Comment by janagyjr** [comment]
Yes, I am still getting the error message of their being no frame from Blender.

**Comment by willyco77** [comment]
Hi, I4m facing similar issue; Could you be more specific about how to update the attribute to align_x
I'm using win and have no ideas how t change such script;
thqnks

**Comment by mixedbredie** [comment]
@willyco77 look at the scripts in C:\Program Files\OpenShot Video Editor\blender\scripts and edit the following files using notepad, notepad2 or notepad++:

blinds, blur, colours, defocus, dissolve, explode, fly_by_1, fly_by_two_titles, glare, glass_slider, halo_zoom_out, neon_curves, rotate_360, trees, wireframe_text and zoom_clapboard.

the text to change is in the Modify Text / Curve settings section (search for ```text_object.align``` or ```spacemode```) and change the ```align``` to ```align_x```.

Take a backup of the files first. Make sure to save them with the .py extension. Restart Openshot and try generate a title.

**Pull request merged**
