### PR TITLE
[WIP] Disable incompatible profiles for existing projects

### PR DESCRIPTION
**Pull request by N3WWN**
This PR will grey out the non-compatible profiles in the Profile dialog for existing projects.  

In this context an "existing project" is one that has not been saved (this is the check I'm currently performing).

The reason behind this change is an attempt to prevent users from changing to profiles with different frame rates, which currently break where keyframes are positioned on the timeline.

Issues that mention this include, but may not be limited to: 

#519 
#640 
#1034  
#1041 
#1098 
#1438

So, the only gotcha is someone who builds a project with keyframed items without saving it.

This PR may need to be modified to look for keyframed items in the project and only restrict the profiles based on if they really are incompatible or not.

### CODE REVIEW

**Comment by N3WWN** [comment]
Hrm... 😕 

I wish there was some way to view the reasons for build failure.

**Comment by DylanC** [comment]
@N3WWN - Yeah I know,  there really should be a way.

**Comment by DylanC** [comment]
@N3WWN - The build is passing again. 😆

**Comment by DylanC** [comment]
@N3WWN - Can you move your old PR's to the develop branch if possible?

**Comment by DylanC** [comment]
@N3WWN - Closing since this relates to master and not develop. Please re-submit if you plan to get this in. Thanks.

**Pull request closed without merging**
