### PR TITLE
Check in "Save Current Frame" feature

### PR DESCRIPTION
**Pull request by N3WWN**
Resubmission of the "Save Current Frame" PR to the develop branch.

This replaces PR #1542 .

This PR addresses the feature request made in Issue #893.

A new preview window button has been added (a camera) which will save the current preview frame (at full profile resolution, regardless of preview quality/scale settings) to the project's current directory or the user's home directory if the project has not yet been saved.

The ability for the user to add a keyboard shortcut has been included, but no keystrokes have been assigned by default.

Presently, the file type is hardcoded to PNG.

A dialog window is shown reporting where the frame was saved or that an error has occurred.

### CODE REVIEW

**Comment by DylanC** [comment]
@N3WWN  Would you be able to have a look at the conflicts when you have a chance?

**Comment by DylanC** [comment]
@N3WWN - Looks like its just the settings related to the nudge clips merge. I'm looking to get this merged next if you have a chance to review first.

**Comment by N3WWN** [comment]
@DylanC - Yup, you are correct.

Hmmm.... I'm not sure if I should click the green "Commit Merge" button after I resolved the conflicts as I think this will actually merge the PR, won't it?

Regardless, here's how it should look at the end of the file:

731-762:

>   {
    "category": "Keyboard",
    "title": "Insert Keyframe",
    "restart": true,
    "setting": "actionInsertKeyframe",
    "value": "Ctrl+Shift+E",
    "type": "text"
  },
  {
    "category": "Keyboard",
    "title": "Save Current Frame",
    "restart": true,
    "setting": "actionSaveFrame",
    "value": "",
    "type": "text"
  },
  {
    "category": "Keyboard",
    "title": "Nudge left",
    "restart": true,
    "setting": "nudgeLeft",
    "value": "Shift+Left",
    "type": "text"
  },
  {
    "category": "Keyboard",
    "title": "Nudge right",
    "restart": true,
    "setting": "nudgeRight",
    "value": "Shift+Right",
    "type": "text"
  }

I included the existing `Insert Keyframe` item so there was some context for what I added.

**Comment by DylanC** [comment]
@N3WWN - Commit merge actually just applies the change as a commit. However, it doesn't merge the PR. I applied the fix for you just now. Do you think this feature is ready to be merged in?

**Comment by N3WWN** [comment]
Thanks @DylanC !  I get a little sheepish when I'm not sure what a button will REALLY do in someone else's repo 😉 

Yes, this PR is ready for merging into `OpenShot:develop`.

**Comment by DylanC** [comment]
@N3WWN - I'm more of a "try something once to see what happens" kinda guy. 😆 Considering it done! (Good sir)

**Comment by Seudodata** [comment]
in Openshot 2.4.1 installed on Ubuntu, I see no such a camera icon. Instead you can do this by:
Export video - advanced - export to: image sequence, then you choose de initial and final frames.

**Comment by ferdnyc** [comment]
@Seudodata

OpenShot 2.4.1 is _incredibly_ out of date, the current release is 2.4.4. This feature was added in 2.4.2 or 2.4.3, I forget which. If it's possible for you to update to a newer version, there have been a lot of improvements since 2.4.1.

**Comment by sz-gabor** [comment]
Ouch, this feature only saves the contents of the currently displayed preview window (as if I pressed PrintScreen), and stretches it to the profile resolution, further degrading its quality. I wondered why are the frames that soft... Could it be fixed in the future to take actual frame data?

**Pull request merged**
