### PR TITLE
Add AppStream metadata

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by eszlari** [comment]
@jonoomph @ferdnyc @DylanC Ping?

**Comment by DylanC** [comment]
@eszlari - Apologies for the delay. Merged! 👍

**Comment by eszlari** [comment]
Could you update `<releases>` when there is a new release?

**Comment by DylanC** [comment]
@eszlari - Yes, we will keep it in mind. Thanks!

**Pull request merged**
