### PR TITLE
Update windows-installer.iss

### LINKED ISSUE #2305: OpenShot on Windows requires undocumented network access
**Describe the bug**
Following installation, the Windows installer complains about requiring network access from launch.exe. Efforts to find documentation supporting this requirement have (so far) proven fruitless.

**System Details:**
 - Windows 7
 - OpenShot Version v2.4.3 for Windows

**To Reproduce**
1. Install OpenShot on Windows 7 from https://www.openshot.org/
2. Once setup is complete, choose "Launch"
3. Observe the Windows Security Alert from "C:\program files\openshot video editor\launch.exe"
4. Notice the "Publisher" for the Windows Security Alert is "Unknown" (read: Unsigned)
5. See screenshot, below.

**Expected behavior**
Network access requirements should be documented, or contain some sort of warning. Windows binaries should be signed by a verifiable publisher.

Current web searches only show typical responses for "trojan'd" software (generally from other scanner output listing OpenShot in the Windows Firewall whitelist, ironically enough).

**Screenshots**
image

**Logs**
N/A

**Additional context**
Hopefully, there's at least a general "README" to be had for non-UNIX users. No apparent requirement in launch.py for network, though that's only a top-level script for python modules, obviously.

It would likely be a good exercise to launch the Linux version and observe the network requirements (which I have yet to do). Unfortunately, the low-level troubleshooting on Windows 7 (and others) often leaves much to be desired.

Assuming this *might* have something related to "Automatically send errors and metrics to OpenShot" (which defaults as "Yes, I would like to improve OpenShot!")... though obviously this action is taken *prior* to actual approval from the user.

### PR DESCRIPTION
**Pull request by dscotese**
Installer now provides a hint about why OS wants a firewall exception.  This is a documentation/UX solution for 

Fixes #2305

### CODE REVIEW

**Comment by dscotese** [comment]
I like @ferdnyc 's suggestion in #3732 to add the word __optional__ so I'm working on doing that without redoing everything else.

**Comment by ferdnyc** [comment]
@dscotese If you go to your fork, select the `develop` branch (since that's the one you opened this PR from, then you can edit the file and when you go to save, you'll have the option to either create a new branch or add a commit on the same branch. If you save to the same branch, the PR will update automatically.

**Comment by ferdnyc** [comment]
:+1: That worked! We just have to let Travis run on it now (even though Travis doesn't even test the `installer/` files...)

**Comment by dscotese** [comment]
Thanks for your help!

**Comment by ferdnyc** [comment]
This looks good to me, I'm going to go ahead and merge it. I'd still like to find a way to set the 'Description' field of the rule itself (as I mentioned in https://github.com/OpenShot/openshot-qt/pull/3732#issuecomment-697988909), but it wasn't immediately obvious how to do that and it's really a separate thing from this change.

Thanks again, @dscotese !

**Pull request merged**
