### PR TITLE
Add controls to temporary disable Audio or Video per Track

### PR DESCRIPTION
**Pull request by SuslikV**
Fixes: https://github.com/OpenShot/openshot-qt/issues/449
...and many related requests.

Skipping also works for export.

OpenShot skip track menu

### CODE REVIEW

**Comment by SuslikV** [comment]
Shifting clip one track up/down doesn't updates skipping yet. I will see if simple fix is possible.

**Comment by SuslikV** [comment]
Clips can be moved from Track to Track now. Skipping streams will update accordingly.

**Comment by SuslikV** [comment]
Current develop was changed. I will update the code later.

**Comment by SuslikV** [comment]
Updated on top of the current _develop_ branch. Should work now.

**Comment by SuslikV** [comment]
Current develop was changed. I will update the code later.

**Comment by SuslikV** [comment]
Updated on top of the current _develop_.

**Comment by jonoomph** [comment]
Closing PR. This could be accomplished with much less code, and probably icons on the track and clip are all we need. But this PR is too complex for my taste. This might be a good PR to model a future change after though, as some of it works fine.

**Pull request closed without merging**
