### PR TITLE
WIP: Generate an updated OpenShot 2.5.1 release AppImage for current OSes

### PR DESCRIPTION
**Pull request by ferdnyc**
This PR is an attempt to get updated builds of `OpenShot-2.5.1-x86_64.AppImage` generated using our current packaging.

The existing 2.5.1 AppImage is not compatible with several recent OS releases, including Ubuntu 20.10 and Fedora 33. But, we're not yet ready to release OpenShot 2.5.2. So I'm hoping that, as a compromise, we can get OpenShot 2.5.1 rebuilt with our current packaging (Python 3.6, updated library bundling) to revive it on the affected systems.

I'm trying to make the changes as minimal as possible here, and focus on updating only the build system, _not_ the OpenShot code itself. But, this is a WIP, and we'll see what becomes necessary.

Outstanding to-dos or potential issues to confirm, before this is ready:

- [X] Update `.gitlab-ci.yml` from the current develop branch
- [ ] Backport _some_ of the changes to `install/build-server.py`
    - [x] The library bundling changes, yes
    - [ ] The webengine inclusion... wait, I was going to say "no", but does the Bionic build server still _have_ webkit installed in PyQt5, under Python 3.6? (It's definitely **possible**, there are still Fedora packages of https://github.com/qtwebkit/qtwebkit even for Fedora 33. But we'll need to get those in place or this idea is dead in the water.)
- [x] Create a branch in the libopenshot repository that rolls it back to 0.2.5-release, since there have been significant changes there as well that we're not yet ready to release.
- [x] I'm hoping libopenshot-audio can stay at its current version.

### CODE REVIEW

**Comment by ferdnyc** [comment]
OK, yes, [python3-pyqt5.qtwebkit](https://packages.ubuntu.com/search?keywords=python3-pyqt5.qtwebkit) _does_ exist for Bionic, and for all Ubuntu releases up to and including Focal, Groovy, and Hirsute. So it can be installed, if it's not currently.

**Comment by ferdnyc** [comment]
I've created a corresponding [branch in the libopenshot project repo](https://github.com/OpenShot/libopenshot/tree/251-appimage-rebuild) that currently holds an exact copy of the `v0.2.5` release branch, so the build servers can use it to build these packages.

**Comment by ferdnyc** [comment]
I just realized that targeting this as a PR against `develop` made no sense. I've retargeted it as a PR against `master`, since if this does succeed it would make sense to merge it into `master` as a bugfix release, until the next release comes along.

**Comment by ferdnyc** [comment]
Looks like, under Travis at least, this now builds. The project build servers are another question...

**Comment by jonoomph** [comment]
Closing this, as I'm about to create a new release branch. 👍

**Pull request closed without merging**
